# Generated by Django 3.2.9 on 2021-11-22 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
